### ISSUE TITLE
MIN SDK VERSION 19?

### ISSUE THREAD

**Issue by TheAnimatrix** [Chrisvin/RubberPicker#6]
While the minimum sdk version is mentioned as 15+, the inner library uses 19? Is this in error or has the min sdk version increased? Thank you, love the effort btw!

**Comment by TheAnimatrix** [comment]
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.github.Chrisvin:RubberPicker:v1.1] C:\Users\TheAnimatrix\.gradle\caches\transforms-2\files-2.1\daf4ec492e1544fcf82ed83698d97c72\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.jem.rubberpicker" to force usage (may lead to runtime failures)

**Comment by Chrisvin** [comment]
My bad, I forgot to update the README after releasing v1.2.
RubberPicker library uses minSdk 15 from v1.2 before which it used minSdk 19.

```
implementation 'com.github.Chrisvin:RubberPicker:v1.2'
```

**Comment by Chrisvin** [comment]
Feel free to reopen if the issue persists/reappears. I'm glad you liked the library, cheers mate.
