### ISSUE TITLE
Default value set error!

### ISSUE THREAD

**Issue by GulmirzaNorboyev** [Chrisvin/RubberPicker#7]
Hello @Chrisvin Jem! RubberPicker, Your library is beautiful, but when I use the starting values, the trackers will stay at the starting point, please clarify! I want to do something like that:

<img width="466" alt="Снимок экрана 2019-12-23 в 7 33 15 PM" src="https://user-images.githubusercontent.com/47708807/71363487-24848c80-25bb-11ea-977c-fc3af363fb01.png">

**Comment by Chrisvin** [comment]
Hi @GulmirzaNorboyev, I'm glad you like the library. There was an issue with `setCurrentStartValue()` & `setCurrentEndValue()` in `RubberRangePicker`.

I've fixed the issue in v1.4 and added the option to set the initial value & `defaultThumbInsideColor` directly in the XML.
```
implementation 'com.github.Chrisvin:rubberpicker:v1.4'
```

You should be able to design your required view along the following lines,
```
<com.jem.rubberpicker.RubberRangePicker
    ...
    app:normalTrackWidth="3dp"
    app:highlightTrackWidth="3dp"
    app:defaultThumbRadius="10dp"
    app:initialStartValue="25"
    app:initialEndValue="75"
    app:normalTrackColor="#d5d5e0"
    app:defaultThumbInsideColor="#ceab86"
    app:highlightTrackColor="#ceab86"
    app:highlightDefaultThumbOnTouchColor="#ceab86"/>
```
